### ISSUE TITLE
demo instructions

### ISSUE THREAD

**Issue by pablodz** [mlan/docker-asterisk#1]
Hello there, 

which extension is used in demo? and how can I connect with Zoiper5

Thanks in advance

**Comment by mlan** [comment]
@pablodz 

The extension that used in the demo is mentioned here [SIP Users](https://github.com/mlan/docker-asterisk/tree/master/src/privatedial#sip-users).

There are several additional steps (like being able to access your server from the internet) needed for a SIP terminal to register successfully. Descriptions of how that is done are available elsewhere. 

If someone know of a good such writeup please share it with us here. 😀

**Comment by pablodz** [comment]
Thanks @mlan
