### ISSUE TITLE
Consider updating to Asterisk 18.20.2

### ISSUE THREAD

**Issue by jadedeane** [mlan/docker-asterisk#11]
Asterisk [18.20.2](https://github.com/asterisk/asterisk/releases/tag/18.20.2) is now available. Please consider updating.

Happy to submit a PR, but wanted to get an idea what your view on 18.x or even 20.x releases was. Thanks.

**Comment by mlan** [comment]
Hello @jadedeane. Many tnanks for your message. I will update the repo shortly.

**Comment by mlan** [comment]
Latest version is now with Asterisk 20.5.2.
