### ISSUE TITLE
make up return error

### ISSUE THREAD

**Issue by fukemy** [mlan/docker-asterisk#13]
Hi, I got this error when try to run `make up`, can you help?
```
Error response from daemon: path /mlan_asterisk/docker-asterisk/demo/pulse is mounted on / but it is not a shared mount
```

**Comment by mlan** [comment]
Hello @fukemy 

Are you running the demo as root? If so you might try to share `/`
```
mount --make-shared /
systemctl daemon-reload
```
This is just a guess since I have not tested this. Perhaps it is better to run the demo as a non privileged user.
