### ISSUE TITLE
Basic setup

### ISSUE THREAD

**Issue by AlexanderZhirov** [mlan/docker-asterisk#3]
Is there any specific example of installation? Forwarding configuration files to the host and so on. A clearer example to use?
It's not entirely clear how to start using an already so complex product, especially in Docker

**Comment by mlan** [comment]
Hi @AlexanderZhirov. I agree, configuring Asterisk is not trivial.

What is your main concern? Is it with editing files within a docker container? Is it with configuring asterisk in general?

Cloning this repository and running the [demo](https://github.com/mlan/docker-asterisk/tree/master/demo) that comes with it allows you to familiarize yourself both with Docker and Asterisk.

Basic setup of Asterisk is described in the section [PrivateDial](https://github.com/mlan/docker-asterisk/tree/master/src/privatedial).

For more details I refer you to the [Asterisk documentation](https://wiki.asterisk.org/wiki/display/AST/Asterisk+Configuration+Files).

Please let me know if you have ideas how we can improve the information available within this repository. 😀

**Comment by AlexanderZhirov** [comment]
@mlan I meant to have a short manual, regarding a clean Asterisk build, only in Docker.
As far as I understand, pure Asterisk does not have configuration files. At least in Alpine, I created them with my own hands and set them up. In theory, can I throw my configuration files inside, through the volume, so that Asterisk can read them? Are there any pitfalls here?

In the test example, you do not specify the volumes so I wondered how well the configuration will be able to work with the data provided?

There are rumors that Asterisk does not work quite stably in Docker.

That's why I suggested creating a simple manual for assembling a simple version using own configuration files.

**Comment by mlan** [comment]
@AlexanderZhirov I think there already is some useful information already in this repository. Please check out what discussed in the section [PrivateDial](https://github.com/mlan/docker-asterisk/tree/master/src/privatedial). 

In the [docker compose example](https://github.com/mlan/docker-asterisk#docker-compose-example) you can study how volumes can be used. I suggest you try the demo as explained [in the same section](https://github.com/mlan/docker-asterisk#docker-compose-example) and use it to tryout your configuration.

Asterisk works in docker. There is some things to consider, see [docker, iptables and docker-proxy](https://github.com/mlan/docker-asterisk#docker-iptables-and-docker-proxy).
