### ISSUE TITLE
issue with ami.class.inc

### ISSUE THREAD

**Issue by nicolasboulet** [mlan/docker-asterisk#7]
Hello,

I've been working with the code from this repository and encountered an error related to a missing file. Specifically, the file ami.class.inc seems to be required by the autoband.php script, but it is not included in the repository. The error message is as follows:

PHP Fatal error:  Uncaught Error: Failed opening required 'ami.class.inc' (include_path='.:/usr/share/php81') in /usr/share/php81/autoband.php:12
Stack trace:
#0 {main}
  thrown in /usr/share/php81/autoband.php on line 1

Could you please provide guidance on how to resolve this issue and how to properly set up the AMI part of the project? Are there specific installation steps or additional dependencies that need to be considered?

Thank you for your assistance.

Best regards,
Nicolas

**Comment by mlan** [comment]
Hello @nicolasboulet.

The submodule `phpami` is needed when building the image. It is updated when you build the image using `make build`. You can check its status by typing `git submodule`.

**Comment by nicolasboulet** [comment]
Hello @mlan ,
Thank you for your help with the phpami submodule the build is going well now
