### ISSUE TITLE
Custom asterisk files

### ISSUE THREAD

**Issue by gmoreno90** [mlan/docker-asterisk#9]
Hi, please could you explain more how I can configure custom asterisk files?
Is mandary to rebuild images when change the src/asterisk config files?
Is possible to send config files when use the demo folder?
Many thanks in advance

**Comment by mlan** [comment]
@gmoreno90 I think your question  is related to persistent storage, which is addressed using [docker volumes](https://docs.docker.com/storage/volumes/). You can see how that is done in the [demo](https://github.com/mlan/docker-asterisk/blob/master/demo/docker-compose.yml).

**Comment by gmoreno90** [comment]
Hi, yes, I edit the question becouse was an error on my side, 
many thanks in advance
